---
name: Action

on: [pull_request]

jobs:

  jira_labeler:
    runs-on: ubuntu-latest
    name: Jira labeler
    steps:
      - uses: actions/checkout@v1
      - uses: gimmyxd/jira_labeler@main
        with:
          repo_token: "${{ secrets.G_TOKEN }}"
          jira_url: "https://tickets.puppetlabs.com:443"
